spring:
  datasource:
    url: jdbc:mysql://localhost:33060/retoback
    username: root
    password: root
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  server:
    contextPath: /MyAppName/v1
  springfox:
    documentation:
      swagger.v2.path: /api-docs

